/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import { paramsForChosenViz } from './AIChartGeneratorModal';

/**
 * A map chart as generated by the backend: its own params have no x_axis or
 * plural metrics, but params_by_viz carries a valid bar-chart config.
 */
const mapChart = {
  viz_type: 'dhis2_map',
  params: {
    viz_type: 'dhis2_map',
    org_unit_column: 'district',
    metric: { expressionType: 'SQL', sqlExpression: 'SUM(cases)' },
  },
  params_by_viz: {
    dhis2_map: {
      viz_type: 'dhis2_map',
      org_unit_column: 'district',
      metric: { expressionType: 'SQL', sqlExpression: 'SUM(cases)' },
    },
    echarts_timeseries_bar: {
      viz_type: 'echarts_timeseries_bar',
      x_axis: 'district',
      metrics: [{ expressionType: 'SQL', sqlExpression: 'SUM(cases)' }],
    },
  },
};

describe('paramsForChosenViz', () => {
  it('returns the chart’s own params when the viz type is unchanged', () => {
    expect(paramsForChosenViz(mapChart, 'dhis2_map')).toBe(
      mapChart.params_by_viz.dhis2_map,
    );
  });

  it('returns the target type’s params on a swap', () => {
    // Regression: the old code spread the map's params into a bar chart, so the
    // saved chart had no x_axis and no metrics.
    const params = paramsForChosenViz(mapChart, 'echarts_timeseries_bar');
    expect(params.x_axis).toBe('district');
    expect(params.metrics).toHaveLength(1);
    expect(params.org_unit_column).toBeUndefined();
  });

  it('falls back to the original params when the target has none', () => {
    expect(paramsForChosenViz(mapChart, 'some_unknown_viz')).toBe(
      mapChart.params,
    );
  });

  it('falls back when params_by_viz is absent entirely', () => {
    const legacy = { viz_type: 'pie', params: { viz_type: 'pie' } };
    expect(paramsForChosenViz(legacy, 'table')).toBe(legacy.params);
  });
});
