#!/usr/bin/env python3
"""Clear erroneous SQL expressions from physical DHIS2 serving columns.

Dry-run is the default. This only updates Superset's PostgreSQL metadata and
never changes ClickHouse tables or saved metric definitions.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from typing import Any

from superset.app import create_app


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dataset-id", action="append", type=int, dest="dataset_ids",
        help="limit repair to one or more SqlaTable IDs",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", dest="apply", action="store_false")
    mode.add_argument("--apply", action="store_true")
    parser.set_defaults(apply=False)
    return parser.parse_args()


def _load_production_environment() -> None:
    env_file = "/etc/superset/superset.env"
    if os.path.exists(env_file):
        with open(env_file, encoding="utf-8") as env_handle:
            for line in env_handle:
                if line.strip() and not line.startswith("#") and "=" in line:
                    key, value = line.strip().split("=", 1)
                    os.environ.setdefault(key, value.strip("\"'"))
    os.environ.setdefault("DHIS2_DISABLE_STARTUP_BACKFILL", "true")


def _is_dhis2_dataset(dataset: Any) -> bool:
    if getattr(dataset, "schema", None) == "dhis2_serving":
        return True
    try:
        extra = json.loads(getattr(dataset, "extra", None) or "{}")
    except (TypeError, json.JSONDecodeError):
        return False
    return bool(extra.get("dhis2_staged_dataset_id") or extra.get("dhis2_serving"))


def _is_physical_column_expression(expression: Any, column_name: str) -> bool:
    """Recognize the erroneous aggregate/bare expressions generated by sync."""
    value = str(expression or "").strip()
    escaped_name = re.escape(column_name)
    return bool(
        re.fullmatch(rf"`?{escaped_name}`?", value, re.I)
        or re.fullmatch(rf"SUM\s*\(\s*`?{escaped_name}`?\s*\)", value, re.I)
    )


def main() -> int:
    args = _parse_args()
    _load_production_environment()
    app = create_app()
    with app.app_context():
        from superset import db
        from superset.connectors.sqla.models import SqlaTable

        query = db.session.query(SqlaTable)
        if args.dataset_ids:
            query = query.filter(SqlaTable.id.in_(list(dict.fromkeys(args.dataset_ids))))

        repaired: list[dict[str, Any]] = []
        skipped: list[dict[str, Any]] = []
        for dataset in query.all():
            if not _is_dhis2_dataset(dataset):
                continue
            changed_columns: list[dict[str, str]] = []
            for column in dataset.columns:
                expression = getattr(column, "expression", None)
                if not expression:
                    continue
                if not _is_physical_column_expression(expression, column.column_name):
                    skipped.append(
                        {
                            "dataset_id": dataset.id,
                            "column_name": column.column_name,
                            "expression": expression,
                            "reason": "not an auto-generated physical-column expression",
                        }
                    )
                    continue
                changed_columns.append(
                    {"column_name": column.column_name, "expression": expression}
                )
                if args.apply:
                    column.expression = None
                if column.column_name == "ou_level" and args.apply:
                    column.groupby = True
                    column.filterable = True
                    column.is_dttm = False
            if changed_columns:
                repaired.append(
                    {
                        "dataset_id": dataset.id,
                        "table_name": dataset.table_name,
                        "columns": changed_columns,
                    }
                )

        if args.apply:
            db.session.commit()
        else:
            db.session.rollback()
        print(
            json.dumps(
                {
                    "mode": "apply" if args.apply else "dry-run",
                    "clickhouse_mutated": False,
                    "datasets_changed": repaired,
                    "nonstandard_expressions_skipped": skipped,
                    "summary": {
                        "datasets": len(repaired),
                        "columns": sum(len(item["columns"]) for item in repaired),
                        "skipped": len(skipped),
                    },
                },
                indent=2,
                default=str,
            )
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
